- package.json
- src/components.d.ts
- src/components/dnn-searchbox/dnn-searchbox.tsx
- src/components/dnn-searchbox/readme.md
- src/index.html
- src/index.ts
- src/utilities/debounce.ts
- yarn.lock
Adds a reusable debounce decorator and implements it in the dnn-searchbox component.
Closes #62
> Created a debounce decorator

- src/utilities/dnnServicesFramework.ts
> Adds services framework utility

- src/index.ts
Closes #83
Fixes an issue where DnnServicesFramework was not exported
> Exports DnnServicesFramework properly

- GitVersion.yml
- package-lock.json
- package.json
- src/components.d.ts
- src/components/dnn-color-picker/dnn-color-picker.scss
- src/components/dnn-color-picker/dnn-color-picker.tsx
- src/components/dnn-color-picker/readme.md
- src/index.html
- src/utilities/colorInfo.spec.ts
- src/utilities/colorInfo.ts
> Implemented color picker

- src/components.d.ts
- src/components/dnn-searchbox/dnn-searchbox.tsx
- src/components/dnn-searchbox/readme.md
> Made searchbox value a prop

- .github/mergeable.yml
Closes #108 
Adds validation of description, label and milestone
> Adds mergeable config

- src/components.d.ts
- src/components/dnn-color-picker/dnn-color-picker.scss
- src/components/dnn-color-picker/dnn-color-picker.tsx
- src/components/dnn-color-picker/readme.md
- src/index.html
> Adds option to set the height of color-picker

- src/components/dnn-color-picker/dnn-color-picker.tsx
> Added shading to color-picker indicator

- src/components.d.ts
- src/components/dnn-sort-icon/dnn-sort-icon.scss
- src/components/dnn-sort-icon/dnn-sort-icon.tsx
- src/components/dnn-sort-icon/readme.md
- src/index.html
Adds a dnn-sort-icon components
> Created dnn-sort-icon

- src/components.d.ts
- src/components/dnn-collapsible/dnn-collapsible.tsx
- src/components/dnn-collapsible/readme.md
- src/index.html
> Fixed an issue with nested collapsible

- GitVersion.yml
Bumps version to 0.8.0 for next release
> Bumps version to 0.8.0 for next release

- src/components.d.ts
- src/components/dnn-toggle/dnn-toggle.scss
- src/components/dnn-toggle/dnn-toggle.tsx
- src/components/dnn-toggle/readme.md
- src/components/dnn-toggle/toggle-interface.ts
- src/index.html
> Created dnn-toggle

- src/components/dnn-collapsible/dnn-collapsible.tsx
- src/index.html
> Fixed an update issue with dnn-collapsible

- GitVersion.yml
Bumps gitversion to 0.9.1 for next release
> Set version to 0.9.1 for next release

- package.json
- src/components/dnn-collapsible/dnn-collapsible.tsx
> Fixes collapsible height update issue.

- src/index.ts
- yarn.lock
Resolves an issue with exporting components
> Resolves an issue with exporting components

- src/index.ts
- yarn.lock
Merge latest changes from Release/0.9.2 into develop
> Merge latest changes from Release/0.9.2 into develop

- .github/dependabot.yml
Changes dependabot config to only warn monthly
> Changes dependabot config to only warn monthly

- README.md
With CI now all setup we have a test site to play with the components and I added a link to it in the readme file together with some nice badges.
Closes #352
> Added test site and link to it in readme

- stencil.config.ts
Greatly improves production debugging
> Added support for sourcemaps

- src/components/dnn-dropzone/dnn-dropzone.scss
- src/components/dnn-dropzone/dnn-dropzone.tsx
- src/index.html
Allows picking, dropping files or optionally taking a picture using the device camera.
> Implemented dnn-dropzone

- _build/Build.cs
- src/components.d.ts
- src/components/dnn-dropzone/dnn-dropzone.scss
- src/components/dnn-dropzone/dnn-dropzone.tsx
- src/components/dnn-image-cropper/dnn-image-cropper.scss
- src/components/dnn-image-cropper/dnn-image-cropper.tsx
- src/index.html
Adds in brower image upload and cropping component.
> Implemented dnn-image-cropper

- src/components/dnn-image-cropper/dnn-image-cropper.tsx
Should make it work on mobile devides
> Adds touche events to dnn-image-cropper

- src/components/dnn-image-cropper/dnn-image-cropper.scss
- src/components/dnn-image-cropper/dnn-image-cropper.tsx
Allows usage on mobile and other touch enabled devices.
> Fixed an issue where touch support would not work with dnn-image-cropper

- src/components/dnn-dropzone/readme.md
- src/components/dnn-image-cropper/readme.md
Forgot to commit a full build so docs where missing
> Commits docs for dnn-dropzone and dnn-image-cropper

- src/components/dnn-dropzone/readme.md
- src/components/dnn-image-cropper/dnn-image-cropper.scss
- src/components/dnn-image-cropper/dnn-image-cropper.tsx
- src/components/dnn-image-cropper/readme.md
Merges latest changes from 0.10.0 into develop
> Merges latest changes from 0.10.0 into develop

- licenses.txt
- package-lock.json
- package.json
There was a higher than supported dependency on eslint that caused multiple warnings.
> Updated dependency chain for linter

- licenses.txt
- src/components.d.ts
- src/components/dnn-tab/dnn-tab.tsx
- src/components/dnn-tab/readme.md
- src/components/dnn-tabs/dnn-tabs.scss
- src/components/dnn-tabs/dnn-tabs.tsx
- src/components/dnn-tabs/readme.md
- src/index.html
> Implemented dnn-tabs

- src/components/dnn-image-cropper/CornerType.ts
- src/components/dnn-image-cropper/dnn-image-cropper.tsx
Refactored the code be better reusability and fixed issues with dragging outside the image.
This makes drags outside the image ignored and also only picks actions back up once back into the surface of the image. Greatly improves ux.
> Fixed an issues where image-crop could not respect ratio

- licenses.txt
- package-lock.json
- package.json
- src/components/dnn-chevron/dnn-chevron.tsx
- src/components/dnn-color-picker/dnn-color-picker.tsx
- src/components/dnn-dropzone/dnn-dropzone.tsx
- src/components/dnn-modal/dnn-modal.tsx
- src/components/dnn-searchbox/dnn-searchbox.tsx
- stencil.config.ts
Merge 0.11.1 fixes to produce 0.11.2
> Merge 0.11.1 fixes to produce 0.11.2

- src/components.d.ts
- src/components/dnn-checkbox/dnn-checkbox.scss
- src/components/dnn-checkbox/dnn-checkbox.tsx
- src/components/dnn-checkbox/readme.md
- src/index.html
Added a dnn-checkbox component that optionally supports tri-state
> Added dnn-checkbox component

- src/components/dnn-checkbox/dnn-checkbox.tsx
Merged v0.12.0 fixes back into develop
> Merged v0.12.0 fixes back into develop

- .github/workflows/Deploy.yml
- README.md
- _build/Build.cs
- licenses.txt
- package-lock.json
- package.json
Also removed personal sponsorship button, switched npm token, and some other things that are non-community related.
> Replaced all Eraware references for DnnCommunity

- _build/Build.cs
A check is done which is case sensitive
> Fixed casing for organization name

- _build/Build.cs
Fixed a versioning issue on NPM
> Fixed a versioning issue on NPM

- _build/Build.cs
> Released v0.13.1

- README.md
> Updated link to docs site

- README.md
Another missed eraware reference
> Another missed eraware reference

- licenses.txt
- src/components.d.ts
- src/components/dnn-image-cropper/dnn-image-cropper.tsx
- src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
- src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
- src/components/dnn-vertical-splitview/readme.md
- src/index.html
- src/utilities/mouseUtilities.ts
Allows splitting a UI in a left and right part with a movable divider.
> implemented dnn-vertical-splitview component

- src/components.d.ts
- src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.scss
- src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.tsx
- src/components/dnn-vertical-overflow-menu/readme.md
- src/index.html
Allows listing menu items and if they do not fit in the menu with, moves them automatically in or out of a dropdown "more" menu.
> Created a vertical-overflow-menu component

- src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
- src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
- src/components/dnn-vertical-splitview/readme.md
- src/index.html
Because of the content being in a slot, it was hard to style the whole panes, so css variables are added to customize the background-color of the panes.
> Changed how to style the pane colors

- src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
This conflicted with flex positioned elements
> Removed left pane 100% height

- src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.scss
- src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.tsx
- src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
- src/index.html
Items need to stay in slots so they can be externally styled
> Fixed multiple style issues with overflow-menu

- src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
- src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
- src/index.html
dnn-vertical-splitview improvements for panes and splitter positioning.
> Fixed some more style issues with splitter

- src/components.d.ts
- src/components/dnn-treeview-item/dnn-treeview-item.scss
- src/components/dnn-treeview-item/dnn-treeview-item.tsx
- src/components/dnn-treeview-item/readme.md
- src/index.html
This allows to monitor for expanded state to run custom behavior externally.
> Added events to treeview expander

- package-lock.json
- src/components/dnn-treeview-item/dnn-treeview-item.scss
Prior to this PR, the first child height was causing it to look a bit off.  Now there is a min-height in the SCSS to ensure it is more uniform.
> Resolve height issue with treeview first child

- src/components/dnn-collapsible/dnn-collapsible.tsx
> Resolve issue with animating collapse of item

- package-lock.json
- src/components.d.ts
- src/components/dnn-collapsible/dnn-collapsible.scss
- src/components/dnn-collapsible/dnn-collapsible.tsx
- src/components/dnn-treeview-item/dnn-treeview-item.scss
- src/components/dnn-treeview-item/dnn-treeview-item.tsx
- src/components/dnn-treeview-item/readme.md
- src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.scss
- src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.tsx
- src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
- src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
- src/components/dnn-vertical-splitview/readme.md
- src/index.html
- stencil.config.ts
Merge latest 0.14.0 fixes back into develop
> Merge latest 0.14.0 fixes back into develop

- src/components/dnn-treeview-item/readme.md
This is a simple update from an automated documentation update for the `treeview-item` component.
> Automated update to treeview-item readme

- src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
> Ensure splitview separator follows changes in element resize

- .storybook/main.js
- src/components/dnn-chevron/dnn-chevron.stories.tsx
- src/components/dnn-collapsible/dnn-collapsible.stories.tsx
- src/components/dnn-color-picker/dnn-color-picker.stories.tsx
- src/components/dnn-dropzone/dnn-dropzone.stories.tsx
- src/components/dnn-image-cropper/dnn-image-cropper.stories.tsx
- src/components/dnn-modal/dnn-modal.stories.tsx
- src/components/dnn-searchbox/dnn-searchbox.stories.tsx
- src/components/dnn-sort-icon/dnn-sort-icon.stories.tsx
- src/components/dnn-tab/dnn-tab.stories.tsx
- src/components/dnn-tabs/dnn-tabs.stories.tsx
- src/components/dnn-toggle/dnn-toggle.stories.tsx
- src/components/dnn-treeview-item/dnn-treeview.stories.tsx
- src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.stories.tsx
- src/components/dnn-vertical-splitview/dnn-vertical-splitview.stories.tsx
This PR adds starting point stories for each component.
> Add starter stories for all components

- .storybook/main.js
- licenses.txt
- package-lock.json
- package.json
Adds accessibility validation in storybook
> Added accessibility validation in storybook

- .storybook/main.js
- .storybook/manager.js
- .storybook/preview-head.html
- .storybook/preview.js
- custom-elements.json
- licenses.txt
- package-lock.json
- package.json
- src/components/dnn-button/dnn-button.stories.ts
- src/components/dnn-button/dnn-button.tsx
- src/components/dnn-collapsible/dnn-collapsible.stories.ts
- stencil.config.ts
* Implemented storybook theme
* Added badges
* Added jsonDocs support and auto import within storybook
* Implemented initial storybook for `dnn-button`
* Implemented config for storybook
* Resolved a few issues with `dnn-button` component
> Storybook theme and features

- src/components/dnn-chevron/dnn-chevron.stories.ts
> Added story for dnn-chevron

- src/components/dnn-color-picker/dnn-color-picker.stories.ts
> Added story for dnn-color-picker

- src/components/dnn-image-cropper/dnn-image-cropper.stories.ts
> Add story for dnn-image-cropper

- src/components/dnn-searchbox/dnn-searchbox.stories.ts
> Added story for `dnn-searchbox`

- src/components.d.ts
- src/components/dnn-modal/dnn-modal.stories.ts
- src/components/dnn-modal/dnn-modal.tsx
> Add story for dnn-modal and update component to add visible prop

- .storybook/utilities.ts
- src/components/dnn-sort-icon/dnn-sort-icon.scss
- src/components/dnn-sort-icon/dnn-sort-icon.stories.ts
Created story for dnn-sort-icon
Also implements a way to have a better ui for css-variables
Closes #512
> Created story for dnn-sort-icon

- src/components/dnn-toggle/dnn-toggle.scss
- src/components/dnn-toggle/dnn-toggle.stories.ts
> Add story for dnn-toggle and resolve a CSS var issue with component

- custom-elements.json
- src/components.d.ts
- src/components/dnn-checkbox/readme.md
- src/components/dnn-collapsible/dnn-collapsible.stories.ts
- src/components/dnn-collapsible/dnn-collapsible.tsx
- src/components/dnn-collapsible/readme.md
- src/components/dnn-dropzone/readme.md
- src/components/dnn-modal/readme.md
- src/components/dnn-permissions-grid/dnn-permissions-grid.stories.ts
- src/components/dnn-searchbox/dnn-searchbox.stories.ts
- src/components/dnn-sort-icon/readme.md
- src/components/dnn-tabs/readme.md
- src/components/dnn-toggle/readme.md
- src/components/dnn-vertical-splitview/readme.md
Fixed multiple missing components declaration in stories
> Fixed multiple missing components declaration in stories

- src/components/dnn-tabs/dnn-tabs.stories.ts
> Add story for `dnn-tabs-story`

- custom-elements.json
- src/components/dnn-checkbox/readme.md
- src/components/dnn-dropzone/readme.md
- src/components/dnn-modal/readme.md
- src/components/dnn-sort-icon/readme.md
- src/components/dnn-tabs/readme.md
- src/components/dnn-toggle/readme.md
- src/components/dnn-vertical-splitview/readme.md
Several readme files needed to be regenerated after the recent changes
> Commits new docs

- custom-elements.json
- licenses.txt
- src/components/dnn-vertical-splitview/dnn-vertical-splitview.scss
- src/components/dnn-vertical-splitview/dnn-vertical-splitview.stories.ts
> Add story for `dnn-vertical-splitview` and resolve CSS var docs issue

- src/components/dnn-treeview-item/dnn-treeview-item.stories.ts
- src/components/dnn-treeview-item/dnn-treeview-item.tsx
- src/components/dnn-treeview-item/readme.md
Added story to dnn-treeview-item
Closes #516
> Added story to dnn-treeview-item

- .gitignore
- _build/Build.cs
- custom-elements.json
- licenses.txt
- package-lock.json
- package.json
Adjusts build to publish the storybook as our demo site.
> Adjusted the build to publish the storybook

- custom-elements.json
- licenses.txt
- src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.scss
- src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.stories.ts
- src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.tsx
- src/components/dnn-vertical-overflow-menu/readme.md
Resolves #517 
It appears there is an issue with the SCSS for `--text-color` and the height for the overflow menu when visible, but we can circle back to these later.
> Add story for `dnn-vertical-overflow-menu` and resolve CSS var issue in component

- package.json
- src/components/dnn-tabs/dnn-tabs.scss
- src/components/dnn-tabs/dnn-tabs.stories.ts
This allows consumers better control over the inner tab content and then can provide their own padding in the slotted content.
> Removed inner padding from dnn-tab

- .eslintrc.js
- licenses.txt
eslint plugin for storybook had a typo
> Corrected plugin name typo

- package-lock.json
- package.json
Appears to fix the "Expecting an HTML snippet or DOM node from the story" issue with Storybook.
> Upgrade `lit-html` to v2.3.1

- licenses.txt
- src/components.d.ts
- src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
- src/index.html
This makes it so consumers can simply use <dnn-monacor-editor /> without any special setup
> Simplifies monaco editor instanciation

- _build/_build.csproj
- custom-elements.json
- licenses.json
- package-lock.json
- package.json
- src/components.d.ts
- src/components/dnn-color-picker/readme.md
- src/components/dnn-image-cropper/readme.md
- src/components/dnn-monaco-editor/dnn-monaco-editor.scss
- src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
- src/components/dnn-monaco-editor/readme.md
- src/components/dnn-tab/readme.md
- stencil.config.ts
Merge `release/0.16.0` into `develop` post v0.16.0 release
> Merge `release/0.16.0` into `develop` post v0.16.0 release

- licenses.json
- package-lock.json
- package.json
- src/components.d.ts
- stencil.config.ts
> Bumped stencil to v3.1.0

- licenses.json
- package-lock.json
- package.json
- src/components.d.ts
> Bumped stencil to v3.2.0

- packages/stencil-library/.storybook/assets/DNNLogo.svg
- packages/stencil-library/.storybook/main.ts
- packages/stencil-library/.storybook/manager.ts
- packages/stencil-library/custom-elements.json
- packages/stencil-library/vscode-data.json
> Resolve broken image for DNN logo in storybook

- packages/stencil-library/src/components/dnn-button/dnn-button.stories.ts
- packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.stories.ts
- packages/stencil-library/src/components/dnn-chevron/dnn-chevron.stories.ts
- packages/stencil-library/src/components/dnn-collapsible/dnn-collapsible.stories.ts
- packages/stencil-library/src/components/dnn-color-picker/dnn-color-picker.stories.ts
- packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.stories.ts
- packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.stories.ts
- packages/stencil-library/src/components/dnn-modal/dnn-modal.stories.ts
- packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.stories.ts
- packages/stencil-library/src/components/dnn-permissions-grid/dnn-permissions-grid.stories.ts
- packages/stencil-library/src/components/dnn-searchbox/dnn-searchbox.stories.ts
- packages/stencil-library/src/components/dnn-sort-icon/dnn-sort-icon.stories.ts
- packages/stencil-library/src/components/dnn-tab/dnn-tab.stories.ts
- packages/stencil-library/src/components/dnn-tabs/dnn-tabs.stories.ts
- packages/stencil-library/src/components/dnn-toggle/dnn-toggle.stories.ts
- packages/stencil-library/src/components/dnn-treeview-item/dnn-treeview-item.stories.ts
- packages/stencil-library/src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.stories.ts
- packages/stencil-library/src/components/dnn-vertical-splitview/dnn-vertical-splitview.stories.ts
All new stories for DNN components.
> All new stories for DNN components.

- .github/workflows/Publish_Site.yml
We need eventually to re-enable actions auto-generation.
> Fixed yaml file for publishing site

- .github/workflows/Publish_Site.yml
Changed Pulish_Site.yml to actually call Nuke target
> Changed Pulish_Site.yml to actually call Nuke target

- .github/workflows/Publish_Site.yml
Fixed a typo in PublishSite.yml
> Fixed a typo in PublishSite.yml

- packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.scss
- packages/stencil-library/src/index.html
> Removed rogue css import

- packages/stencil-library/src/components/dnn-button/dnn-button.tsx
Changed order and colors of dnn-button modal
Closes #680
> Changed order and colors of dnn-button modal

- packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
- packages/stencil-library/src/components/dnn-modal/dnn-modal.scss
- packages/stencil-library/src/components/dnn-modal/dnn-modal.tsx
Makes dnn-Modal resizable.
resolves #541.
> Makes dnn-Modal resizable.

- packages/stencil-library/src/components/dnn-collapsible/dnn-collapsible.stories.ts
- packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
- packages/stencil-library/src/components/dnn-modal/dnn-modal.scss
- packages/stencil-library/src/components/dnn-modal/dnn-modal.tsx
Added a better template example for dnn-collapsible.
Closes #719 .
> dnn-collapsible story changes

- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-button/dnn-button.scss
- packages/stencil-library/src/components/dnn-button/dnn-button.tsx
Made dnn-button disabled more disabled.
Closes #718 .
> Made dnn-button disabled more disabled.

- packages/stencil-library/src/components/dnn-treeview-item/dnn-treeview-item.stories.ts
added dnn-treeview story templates.
Closes #722 .
> added dnn-treeview story templates.

- packages/stencil-library/src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.stories.ts
Added vertical splitview for dnn-vertical-overflowmenu.
Closes #723 .
> Added vertical splitview for dnn-vertical-overflowmenu.

- packages/stencil-library/custom-elements.json
- packages/stencil-library/src/components/dnn-tab/dnn-tab.stories.ts
- packages/stencil-library/src/components/dnn-tabs/dnn-tabs.stories.ts
Fixed Tabs and Tab story structure.
Closes #721 .
> Fixed Tabs and Tab story structure.

- packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.stories.ts
Image cropper amelioration.   
Added new and functional buttons for the image cropper storybook.
Closes #720 .
> Image cropper amelioration

- packages/react-library/lib/components/stencil-generated/index.ts
- packages/stencil-library/custom-elements.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.tsx
- packages/stencil-library/src/components/dnn-modal/dnn-modal.tsx
- packages/stencil-library/src/components/dnn-select/dnn-select.scss
- packages/stencil-library/src/components/dnn-select/dnn-select.stories.ts
- packages/stencil-library/src/components/dnn-select/dnn-select.tsx
- packages/stencil-library/src/components/dnn-select/readme.md
- packages/stencil-library/src/index.html
- packages/stencil-library/vscode-data.json
> Implemented dnn-select

- packages/stencil-library/src/components/dnn-input/dnn-input.scss
- packages/stencil-library/src/components/dnn-select/dnn-select.scss
Fixed spacing issues with dnn-input and dnn-select
> Fixed spacing issues with dnn-input and dnn-select

- packages/stencil-library/src/index.html
> Adjusted color system as discussed

- packages/stencil-library/custom-elements.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-button/dnn-button.scss
- packages/stencil-library/src/components/dnn-button/dnn-button.stories.ts
- packages/stencil-library/src/components/dnn-button/dnn-button.tsx
- packages/stencil-library/src/components/dnn-button/readme.md
- packages/stencil-library/src/index.html
- packages/stencil-library/vscode-data.json
Added a danger variant to dnn-button.
> Added a danger variant to dnn-button.

- packages/stencil-library/src/components/dnn-select/dnn-select.tsx
Dnn select doesn't update fix. [OS-3]
> Dnn select doesn't update fix

- package-lock.json
- packages/react-library/lib/components/stencil-generated/react-component-lib/utils/attachProps.ts
- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/package.json
Bumps Stencil to v4.0.1 as per migration guide
supersedes #751
> Bumps Stencil to v4.0.1 as per migration guide

- packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
- packages/stencil-library/src/index.html
Improved dnn-image-cropper so it can work without a crop ratio too
> Improved dnn-image-cropper so it can work without a crop ratio too

- packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
Dnn image cropper non-image files fix
Closes #775.
> Dnn image cropper non-image files fix

- packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.scss
- packages/stencil-library/src/components/dnn-chevron/dnn-chevron.scss
- packages/stencil-library/src/components/dnn-select/dnn-select.scss
- packages/stencil-library/src/components/dnn-sort-icon/dnn-sort-icon.scss
- packages/stencil-library/src/components/dnn-tabs/dnn-tabs.scss
Makes clickable elements appear as clickable.
Closes #774.
> Makes clickable elements appear as clickable.

- package-lock.json
- packages/stencil-library/package.json
> Bumped typescript to v5.0.4

- packages/stencil-library/custom-elements.json
- packages/stencil-library/src/index.ts
- packages/stencil-library/vscode-data.json
On consuming projects it complain it can't find jodit/types from node_modules. I am not 100% sure this is the way to do it, but will test it out shortly...
> Added jodit/types to exports

- packages/stencil-library/custom-elements.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-richtext/dnn-richtext-config.ts
- packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
- packages/stencil-library/src/components/dnn-richtext/readme.md
- packages/stencil-library/src/index.ts
Need to merge to test this out.
> Attempting to inherit jodit config

- packages/stencil-library/custom-elements.json
- packages/stencil-library/package.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-richtext/dnn-richtext-config.ts
- packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
- packages/stencil-library/src/components/dnn-richtext/readme.md
[Use tyeof instead of importing type](https://github.com/DNNCommunity/dnn-elements/commit/3b66cb27017441a70d4a0394cf9e846a614b4185)
> Use tyeof instead of importing type

- packages/stencil-library/package.json
> Add-back Jodit

- package-lock.json
- packages/stencil-library/package.json
> Made Jodit a hard dependency

- packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
export only config type from jodit
> export only config type from jodit

- packages/stencil-library/src/components/dnn-input/dnn-input.scss
- packages/stencil-library/src/components/dnn-select/dnn-select.scss
Merged `release/0.20.2` into `main` to release `v0.20.2`
> Merged `release/0.20.2` into `main` to release `v0.20.2`

- packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
in Firefox
Fixed a flaky behavior from cropper in Firefox
> Fixed a flaky behavior from cropper

- packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
Merged `release/0.21.1` into `main` to release `v0.21.1`
> Merged `release/0.21.1` into `main` to release `v0.21.1`

- _build/_build.csproj
- global.json
> Bumps Nuke to v7.0.6

- packages/react-library/lib/components/stencil-generated/index.ts
- packages/stencil-library/custom-elements.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-button/readme.md
- packages/stencil-library/src/components/dnn-color-input/dnn-color-info.ts
- packages/stencil-library/src/components/dnn-color-input/dnn-color-input.scss
- packages/stencil-library/src/components/dnn-color-input/dnn-color-input.stories.ts
- packages/stencil-library/src/components/dnn-color-input/dnn-color-input.tsx
- packages/stencil-library/src/components/dnn-color-input/readme.md
- packages/stencil-library/src/components/dnn-color-picker/readme.md
- packages/stencil-library/src/components/dnn-modal/readme.md
- packages/stencil-library/src/components/dnn-tab/readme.md
- packages/stencil-library/src/components/dnn-tabs/readme.md
- packages/stencil-library/src/index.html
- packages/stencil-library/vscode-data.json
Allows picking one or multiple colors for a color system. Can be used in a form to look like other dnn-inputs
> Added dnn-color-input element

- packages/stencil-library/src/components/dnn-color-input/dnn-color-input.scss
- packages/stencil-library/src/components/dnn-input/dnn-input.scss
- packages/stencil-library/src/components/dnn-select/dnn-select.scss
Adjusted an incorrect label alignment with input fields.
Closes #824
> Adjusted an incorrect label alignment with input fields

- README.md
- packages/react-library/README.md
- packages/stencil-library/README.md
In preparation for DNN 10, we needed to clean up the README files.  As a result of converting this to a monorepo, a few details like this were missed.
Resolves #903
> Refine readme files for published npm packages a repo

- .gitignore
- _build/_build.csproj
- build.sh
- global.json
> Updated Nuke to v8.0.0

- packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.tsx
- packages/stencil-library/src/components/dnn-image-cropper/types.ts
Merged `release/0.23.3` into `main` to release `v0.23.3`
> Merged `release/0.23.3` into `main` to release `v0.23.3`

- _build/_build.csproj
- build.ps1
- build.sh
- package-lock.json
- packages/react-library/package.json
- packages/stencil-library/licenses.json
- packages/stencil-library/package-lock.json
- packages/stencil-library/package.json
- packages/stencil-library/src/components/dnn-input/readme.md
- packages/stencil-library/src/components/dnn-vertical-splitview/readme.md
In an earlier PR, Nuke was updated but somehow not totally (bootstraping scripts and .Net runtime)
> Properly completed Nuke update to v8

- _build/Build.cs
- packages/react-library/lib/components/stencil-generated/index.ts
- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-button/readme.md
- packages/stencil-library/src/components/dnn-checkbox/readme.md
- packages/stencil-library/src/components/dnn-color-input/readme.md
- packages/stencil-library/src/components/dnn-dropzone/readme.md
- packages/stencil-library/src/components/dnn-image-cropper/readme.md
- packages/stencil-library/src/components/dnn-input/readme.md
- packages/stencil-library/src/components/dnn-select/readme.md
- packages/stencil-library/src/components/dnn-toggle/readme.md
- packages/stencil-library/src/components/dnn-vertical-splitview/readme.md
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.scss
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.stories.ts
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
- packages/stencil-library/src/components/examples/dnn-example-form/readme.md
- packages/stencil-library/src/index.html
- packages/stencil-library/vscode-data.json
This allows better testing for interactions/styling of various individual components when used together in a form.
> Implemented form example

- packages/stencil-library/src/components/dnn-tabs/readme.md
> Resolved typo in HTML example for dnn-tabs and added TSX example

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components/dnn-richtext/readme.md
- packages/stencil-library/src/components/dnn-tabs/readme.md
- packages/stencil-library/src/components/dnn-tabs/usage/HTML.md
- packages/stencil-library/src/components/dnn-tabs/usage/JSX-TSX.md
- packages/stencil-library/src/components/examples/dnn-example-form/readme.md
- packages/stencil-library/vscode-data.json
> Implemented Usage documentation for dnn-tabs

- packages/stencil-library/src/components/dnn-button/readme.md
- packages/stencil-library/src/components/dnn-button/usage/HTML.md
- packages/stencil-library/src/components/dnn-button/usage/JSX-TSX.md
> Implemented usage documentation for dnn-button

- packages/stencil-library/custom-elements.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-select/dnn-select.tsx
- packages/stencil-library/src/components/dnn-select/readme.md
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
Closes dnn-select needs a method to trigger validation #959
> Improved validation support of dnn-select

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components/dnn-checkbox/readme.md
- packages/stencil-library/src/components/dnn-checkbox/usage/HTML.md
- packages/stencil-library/src/components/dnn-checkbox/usage/JSX-TSX.md
- packages/stencil-library/vscode-data.json
> Implemented usage documentation for `dnn-checkbox`

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components/dnn-chevron/readme.md
- packages/stencil-library/src/components/dnn-chevron/usage/HTML.md
- packages/stencil-library/src/components/dnn-chevron/usage/JSX-TSX.md
- packages/stencil-library/vscode-data.json
> Implemented usage documentation for `dnn-chevron`

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components/dnn-collapsible/readme.md
- packages/stencil-library/src/components/dnn-collapsible/usage/HTML.md
- packages/stencil-library/src/components/dnn-collapsible/usage/JSX-TSX.md
- packages/stencil-library/vscode-data.json
> Implemented usage documentation for `dnn-collapsible`

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.tsx
- packages/stencil-library/src/components/dnn-image-cropper/readme.md
- packages/stencil-library/src/index.html
- packages/stencil-library/src/utilities/fileUtilities.ts
- packages/stencil-library/vscode-data.json
This allows consumers to get more info about the image, like the file name, type, size and  other metadata and methods.
Additionally it uses that file object in the form value instead of just the string.
> Added event to expose File object in dnn-image-cropper

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components/dnn-toggle/readme.md
- packages/stencil-library/src/components/dnn-toggle/usage/HTML.md
- packages/stencil-library/src/components/dnn-toggle/usage/JSX-TSX.md
- packages/stencil-library/vscode-data.json
> Implemented Usage documentation for dnn-toggle

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components/dnn-input/dnn-input.tsx
- packages/stencil-library/src/components/dnn-toggle/readme.md
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
- packages/stencil-library/vscode-data.json
> Fixed display of dnn-input validation messages

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components/dnn-color-picker/readme.md
- packages/stencil-library/src/components/dnn-color-picker/usage/HTML.md
- packages/stencil-library/src/components/dnn-color-picker/usage/JSX-TSX.md
- packages/stencil-library/vscode-data.json
> Implemented `Usage` documentation for `dnn-color-picker`

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components/dnn-monaco-editor/readme.md
- packages/stencil-library/src/components/dnn-monaco-editor/usage/HTML.md
- packages/stencil-library/src/components/dnn-monaco-editor/usage/JSX-TSX.md
- packages/stencil-library/vscode-data.json
> Implemented `Usage` documentation for `dnn-monaco-editor`

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/components/dnn-progress-bar/readme.md
- packages/stencil-library/src/components/dnn-progress-bar/usage/HTML.md
- packages/stencil-library/src/components/dnn-progress-bar/usage/JSX-TSX.md
- packages/stencil-library/vscode-data.json
> Implemented `Usage` documentation for `dnn-progress-bar`

- CONTRIBUTING.md
> Update security URL

- packages/stencil-library/src/components/dnn-button/dnn-button.scss
- packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.scss
- packages/stencil-library/src/components/dnn-chevron/dnn-chevron.scss
- packages/stencil-library/src/components/dnn-modal/dnn-modal.scss
- packages/stencil-library/src/components/dnn-searchbox/dnn-searchbox.scss
- packages/stencil-library/src/components/dnn-sort-icon/dnn-sort-icon.scss
- packages/stencil-library/src/components/dnn-tabs/dnn-tabs.scss
- packages/stencil-library/src/components/dnn-toggle/dnn-toggle.scss
> Updated to utilize `focus-visible` styles instead of `focus`

- package-lock.json
- packages/stencil-library/package.json
- packages/stencil-library/src/components/dnn-richtext/dnn-richtext.scss
- packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
- packages/stencil-library/src/index.html
dnn-richtext uses Jodit and it was not hooked properly into the shadow root which would cause some styles and behaviour issues. Also the events were wrong and not emiting a string but the inner event.
> Fixed an issue with usage of richtext in shadowRoot

- .github/workflows/Deploy.yml
- .github/workflows/PR_Validation.yml
- .github/workflows/Publish_Site.yml
- .nuke/build.schema.json
- _build/_build.csproj
- global.json
- package-lock.json
- packages/react-library/lib/components/stencil-generated/react-component-lib/attachProps.ts
- packages/react-library/lib/components/stencil-generated/react-component-lib/case.ts
- packages/react-library/lib/components/stencil-generated/react-component-lib/dev.ts
- packages/react-library/lib/components/stencil-generated/react-component-lib/index.tsx
- packages/react-library/package.json
- packages/stencil-library/licenses.json
- packages/stencil-library/package.json
> Bumped Nuke to 8.1.0

- packages/stencil-library/src/index.html
This was discusses in last co-coding to make sure we can support very different themes like light/dark/hi-contrast, etc.
Closes #1174
> Added some more css-variables

- packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.tsx
- packages/stencil-library/src/components/dnn-input/dnn-input.tsx
- packages/stencil-library/src/components/dnn-textarea/dnn-textarea.tsx
Closes setCustomValidity("") does not remove the red border until blur https://github.com/DNNCommunity/dnn-elements/issues/1176
> Fixed some issues to reset custom validity

- packages/stencil-library/src/components/dnn-select/dnn-select.tsx
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
Also fixes same for dnn-autocomplete.
Fixed dnn-select and dnn-autocomplete should validate upon blur #1175
> Fixed display of invalid on bluring dnn-select

- packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.tsx
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
Closes dnn-autocomplete, dropdown should show selections #1180
> dnn-autocomplete, allow showing suggestions upon click

- packages/stencil-library/custom-elements.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-textarea/dnn-textarea.scss
- packages/stencil-library/src/components/dnn-textarea/dnn-textarea.tsx
- packages/stencil-library/src/components/dnn-textarea/readme.md
- packages/stencil-library/vscode-data.json
Closes dnn-textarea needs better height support and other css polishing #1178
> Fixed some css issues with dnn-textarea

- packages/stencil-library/custom-elements.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.tsx
- packages/stencil-library/src/components/dnn-checkbox/readme.md
- packages/stencil-library/src/components/dnn-permissions-grid/dnn-permissions-grid.scss
- packages/stencil-library/src/components/dnn-permissions-grid/dnn-permissions-grid.tsx
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
> Changed label support for dnn-checkbox

- packages/stencil-library/src/components/dnn-toggle/dnn-toggle.tsx
> Allows toggle to be wrapped in label

- packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.tsx
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
- Required now properly reports being invalid
- Fixed multiple glitches to allow either picking an item or using free-text
> Improved autocomplete behaviour

- _build/_build.csproj
- global.json
- package-lock.json
- packages/react-library/package.json
- packages/stencil-library/licenses.json
- packages/stencil-library/package.json
> Bumped nuke to v8.1.2

- .hintrc
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.tsx
- packages/stencil-library/src/components/dnn-select/dnn-select.tsx
Added autocomplete prop to dnn-select and dnn-autocomplete Closes #1198
> Added autocomplete prop to dnn-select and dnn-autocomplete

- packages/stencil-library/src/components/dnn-input/dnn-input.tsx
> Fixed an issue with input of negative numbers

- packages/stencil-library/src/components/dnn-input/dnn-input.tsx
Still about #1212 complete fix.
> Additional fix the the label floating issue on 0

- packages/stencil-library/src/components/dnn-select/dnn-select.tsx
> Fixed a validation issue with dnn-select

- .nuke/build.schema.json
- _build/Build.cs
- _build/_build.csproj
- global.json
- package-lock.json
- packages/react-library/lib/components/stencil-generated/index.ts
- packages/react-library/package.json
- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/package.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-button/readme.md
- packages/stencil-library/src/components/dnn-select/readme.md
- packages/stencil-library/src/components/test-form/readme.md
- packages/stencil-library/src/components/test-form/test-form.scss
- packages/stencil-library/src/components/test-form/test-form.tsx
- packages/stencil-library/src/index.html
- packages/stencil-library/stencil.config.ts
- packages/stencil-library/vscode-data.json
> Bumped nuke to v9.0.3

- packages/stencil-library/custom-elements.json
- packages/stencil-library/licenses.json
- packages/stencil-library/src/index.html
- packages/stencil-library/vscode-data.json
This PR handles the following:
* Updated hard-coded CSS variables in `index.html` to match those in DNN 10.
* Updated the body font size to properly handle the numeric value of `--dnn-base-font-size`.
Resolves #1248
> Updated hard-coded CSS variables in `index.html` to match those in DNN 10

- packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.scss
- packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.tsx
- packages/stencil-library/src/components/dnn-input/dnn-input.tsx
- packages/stencil-library/src/components/dnn-modal/dnn-modal.tsx
- packages/stencil-library/src/components/dnn-textarea/dnn-textarea.scss
- packages/stencil-library/src/components/dnn-textarea/dnn-textarea.tsx
> Harmonized styles of invalid across components

- packages/stencil-library/custom-elements.json
- packages/stencil-library/src/components.d.ts
- packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.scss
- packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.stories.ts
- packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.tsx
- packages/stencil-library/src/components/dnn-checkbox/readme.md
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
- packages/stencil-library/vscode-data.json
Added support for "required" for dnn-checkbox
Closes #1266
> Added support for "required" for dnn-checkbox

- packages/stencil-library/package.json
Updates develop with latest fixes from v0.27.0
> Updates develop with latest fixes from v0.27.0

- package-lock.json
- packages/stencil-library/package.json
- packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
> Bumped jodit to v4.6.2

- packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
Fixed some safari issues with dnn-richtext
> Fixed some safari issues with dnn-richtext

- packages/stencil-library/src/utilities/stringUtilities.ts
Fixed an issue that prevented proper initialization of dnn-richtext
> Fixed an issue that prevented proper initialization of dnn-richtext

- package-lock.json
- packages/stencil-library/.storybook/main.ts
- packages/stencil-library/eslint.config.ts
- packages/stencil-library/package.json
- packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.stories.ts
- packages/stencil-library/src/components/dnn-button/dnn-button.stories.ts
- packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.stories.ts
- packages/stencil-library/src/components/dnn-chevron/dnn-chevron.stories.ts
- packages/stencil-library/src/components/dnn-collapsible/dnn-collapsible.stories.ts
- packages/stencil-library/src/components/dnn-color-input/dnn-color-input.stories.ts
- packages/stencil-library/src/components/dnn-color-picker/dnn-color-picker.stories.ts
- packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.stories.ts
- packages/stencil-library/src/components/dnn-image-cropper/dnn-image-cropper.stories.ts
- packages/stencil-library/src/components/dnn-input/dnn-input.stories.ts
- packages/stencil-library/src/components/dnn-modal/dnn-modal.stories.ts
- packages/stencil-library/src/components/dnn-permissions-grid/dnn-permissions-grid.stories.ts
- packages/stencil-library/src/components/dnn-progress-bar/dnn-progress-bar.stories.ts
- packages/stencil-library/src/components/dnn-searchbox/dnn-searchbox.stories.ts
- packages/stencil-library/src/components/dnn-select/dnn-select.stories.ts
- packages/stencil-library/src/components/dnn-sort-icon/dnn-sort-icon.stories.ts
- packages/stencil-library/src/components/dnn-tab/dnn-tab.stories.ts
- packages/stencil-library/src/components/dnn-tabs/dnn-tabs.stories.ts
- packages/stencil-library/src/components/dnn-textarea/dnn-textarea.stories.ts
- packages/stencil-library/src/components/dnn-toggle/dnn-toggle.stories.ts
- packages/stencil-library/src/components/dnn-treeview-item/dnn-treeview-item.stories.ts
- packages/stencil-library/src/components/dnn-vertical-overflow-menu/dnn-vertical-overflow-menu.stories.ts
- packages/stencil-library/src/components/dnn-vertical-splitview/dnn-vertical-splitview.stories.ts
- packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.stories.ts
- packages/stencil-library/types/raw-md.d.ts
Some things have change on how to load markdown content with the vite builder
> Fixed storybook (again)
