DNNCommunity/dnn-elements

src/components/dnn-modal/dnn-modal.scss
Caused by bootstrap .modal display: none on the .modal class and
only affected by browsers that do not support shadowDOM like
IE and Edge
=> Fixes modal display issue with Edge and Bootstrap

src/components/dnn-collapsible/dnn-collapsible.tsx
Closes #112
Content was hidden before expansion
which made the height calculation impossible
=> Fixed an issue with missing collapsible content

src/utilities/dnnServicesFramework.ts
Fixed usage of dnn services framework in an iframe, required for usage in the persona bar.
Closes #280
=> Fixed usage of dnn services framework in an iframe

src/components/dnn-image-cropper/dnn-image-cropper.tsx
Safari and IE are the only browsers that do not support TouchEvent, this PR does a check for the existance of that interface before using it.
=> Fixed an issue with dnn-image-crop not working in safari

licenses.txt, package-lock.json, package.json, src/components.d.ts, src/components/dnn-chevron/dnn-chevron.scss, src/components/dnn-chevron/dnn-chevron.tsx, src/components/dnn-color-picker/dnn-color-picker.scss, src/components/dnn-color-picker/dnn-color-picker.tsx, src/components/dnn-dropzone/dnn-dropzone.tsx, src/components/dnn-dropzone/readme.md, src/components/dnn-modal/dnn-modal.tsx, src/components/dnn-searchbox/dnn-searchbox.tsx, stencil.config.ts
This changes most inline svg icons into the material icons svg npm package.
This is a potential breaking change from consumers of this library as you will either end up with an inline svg or a base64 data-url depending on how this is consumed which may affect how the css works out. In theory because we are in shadow-dom, it should not be an issue but it is worth testing before upgrading to this new version.
For stenciljs consumers of this package you can simply
`npm install stencil-inline-svg --save-dev` and call it in your stencil config plugins, for usage in other frameworks, please open an issue with minimal usage scenario for help.
=> Implemented material icons package

.gitignore, _build/Build.cs
This fixes an npm release versioning issue.
=> Run TagRelease before Build

licenses.txt, package-lock.json, package.json
- Moved material design icons package from `dev-dependencies` to `dependencies`
- Bumped from v0.10.1 to v0.10.5
Closes #417
=> Fixed an issue that prevented icons from showing on consumers

licenses.txt, package-lock.json, package.json, src/components/dnn-chevron/dnn-chevron.tsx, src/components/dnn-color-picker/dnn-color-picker.tsx, src/components/dnn-dropzone/dnn-dropzone.tsx, src/components/dnn-modal/dnn-modal.tsx, src/components/dnn-searchbox/dnn-searchbox.tsx, stencil.config.ts
Consumers of this package would have to do something special on their hand and since these components need to be universal, I do not want this situation.
This PR removes the svg module and the inline-svg bundling and brings back normal svgs inline in the render method.
This feature might come back if https://github.com/fabriciomendonca/stencil-inline-svg/issues/5 gets resolved.
=> Removed stencil-inline-svg due to a bug

src/components/dnn-image-cropper/dnn-image-cropper.tsx
TouchEvent is not supported on firefox which caused the dragging code to fail. Also changing an image src to a data-url is not instant in firefox so had to attach a load event on it to run the logic only after the image is fully loaded.
=> Fixed an issue that prevented cropping images on firefox

src/components/dnn-image-cropper/dnn-image-cropper.tsx
Before this change the crop corner could be partially outside the image which would disable the drag. This makes it so if the mouse is outside the image but still inside of a corner of the cropper, it still works and makes it easier to grab.
=> Improved corner grap capability

_build/Build.cs
The Tag target could fire up in any order, this makes it always run before compile and the deploy task depend on compile too so the build is tested before deployment.
Closes #423
=> Fixed an issue where CI would not change package version

src/components/dnn-checkbox/dnn-checkbox.tsx
When undefined, will move to checked state instead of unchecked state when clicked.
=> Changed state ordering for dnn-checkbox

licenses.txt, src/components/dnn-image-cropper/dnn-image-cropper.tsx, src/components/dnn-tabs/dnn-tabs.tsx, src/components/dnn-treeview-item/dnn-treeview-item.tsx, src/components/dnn-vertical-splitview/dnn-vertical-splitview.tsx
A warning shows whenever a state that triggers a re-render happens as it is usually something that should be done before rendering and an extra render can be avoided by moving it to another lifecycle event. However in some cases it does make sense to re-render on purpose. The way to avoid the warning is to wrap the method in a requestAnimationFrame promise so that the state changes when we are sure the initial rendering is totally complete. It does not change much as it still re-renders but it kinda declares that it was on purpose and we know what we are doing. This way the warning goes away.
=> Resolved multiple warnings about changing state during render

stencil.config.ts
To be used in a wider range of scenarios this will also emit es5 packages but in production builds only so to not slow down development.
Closes #455
=> Build es5 components for production

src/components/dnn-collapsible/dnn-collapsible.scss, src/components/dnn-collapsible/dnn-collapsible.tsx, src/index.html
This refactors the collapsible component to be more simple and fixes an issue with nesting collapsible in a certain way where parents would not update their size properly if the contents of slots are dynamically changed at runtime.
The behaviour here is that it will transition to the height of the knows content but afterwards will release the fixed size and just snap to the new content should it change dynamically. We win in usability here but have a small snap UI effect in some situations. I would like to improve this one day, but for now, this makes it more usable.
=> Resolved collapsible nesting issues

src/components.d.ts, src/components/dnn-treeview-item/dnn-treeview-item.tsx
Now there is a mechanism for the consumer to manage the collapsing and expansion of treeview item nodes.  This PR adds a `Watch` on the `expanded` property and handles accordingly.
=> Add watch for expanded prop and handle accordingly

src/components/dnn-treeview-item/dnn-treeview-item.tsx
A `setTimeout` was removed previously that is evidently needed for the `ComponentDidLoad` event.  This ensures a treeview item that is initially expanded is handled properly.
=> Resolve issue with initial expanded treeview item

src/components/dnn-chevron/dnn-chevron.stories.ts, src/components/dnn-tab/dnn-tab.stories.ts
Resolves #513 
Also resolved a minor issue with `dnn-chevron` regarding dash casing for props.
One thing to note about this one is that it is intended for use with `dnn-tabs` and will not show the component on the `Canvas` or `Docs` (because by default it's `visible` state is `false`).
=> Add story for `dnn-tab`

src/components/dnn-modal/dnn-modal.scss
In some situation using in DNN many surounding elements can have a z-index of 1000+ (menus, floats, other modal, etc.) So this raises the default modal overlay to z-index of 1002.
This is to fix https://github.com/dnnsoftware/Dnn.Platform/issues/5290
=> Raised modal z-index

licenses.txt, src/components/dnn-modal/dnn-modal.scss, src/components/dnn-modal/dnn-modal.tsx, src/index.html
The modal will now show scrollbars should it's content be wider or longer than 80% of the viewport
=> Adjusted modal behavior to allow oversized content

licenses.json, package-lock.json, src/components.d.ts, src/components/dnn-color-picker/readme.md, src/components/dnn-image-cropper/readme.md, src/components/dnn-monaco-editor/dnn-monaco-editor.scss, src/components/dnn-monaco-editor/dnn-monaco-editor.tsx, src/components/dnn-tab/readme.md, stencil.config.ts
This copies some assets needed on the page level and loads them in the page head if the editor is used on the page.
The monaco css also requires a font and it is expected to live in a very specific relative path so files need to be manually copied into specific folders.
It also looks like a full build was not run before the beta release, so some docs were not auto-generated on other components earlier.
Also I added a new method to allow consumers to change the code content after the component is already loaded.
=> Fixed a few assets paths issues for monaco-editor

custom-elements.json, src/components/dnn-monaco-editor/dnn-monaco-editor.scss, src/components/dnn-monaco-editor/dnn-monaco-editor.tsx, src/components/dnn-monaco-editor/readme.md, stencil.config.ts
1. In a previous attempt, we were distributing the monaco CSS file as an asset but in DNN context we had no great way to know in which path those files would actually live as we are producing components and not a website. So I reverted to using an scss import as that part was working right, it's only the font that was not working
2. In order to fix the font I discovered that chrome has a bug with fonts defined inside shadow-root and the workaround is to use scripts to import the font on the document head. I learned that one can use `import.meta.url` in the context of es-modules to get the URL to the module and not the page or otherwise.
3. For assets paths, since we have no clue where the path would be for a consumer, I learned that one can use `import.meta.url` inside an es-module to get …
=> More monaco fixes

custom-elements.json, licenses.json, src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
Changed class name for the `dnn-monaco-editor` component from `MonacoEditor` to `DnnMonacoEditor`.  This naming convention is consistent with all the other `dnn-elements` components.
=> Fixed class name for `dnn-monaco-editor`

_build/_build.csproj
The version of GitVersion that was used targetted .Net 5 and Github recently removed that version from runners. This attempts to upgrade GitVersion to see if it now targets .Net 6
=> Updates GitVersion

custom-elements.json, src/components.d.ts, src/components/dnn-monaco-editor/dnn-monaco-editor.tsx, src/components/dnn-monaco-editor/readme.md
The `codicon.ttf` file was not, by default, accessible for consumers.  Therefore, we needed to default loading the font from CDN.  We opted for using the font from the `monaco-editor` repo.  We will need to keep the version in the `unpkg` URL in sync with the version of `monaco-editor` being used in `dnn-elements`.
=> Implemented loading `codicon.ttf` from CDN and local

.storybook/assets/DNNLogo.svg, .storybook/main.js, .storybook/manager.js, licenses.json
This PR implements the use of `staticDirs` for utilizing local assets and deploying them to the storybook site.
=> Resolve issue with logo by using local assets in storybook

.storybook/main.js, .storybook/manager.js
This PR attempts to resolve the path issues to the logo asset on GitHub Pages.  It also attempts to ensure the web components dist is copied over to the site branch in the same way assets are now handled.
=> Resolve GitHub Pages path to assets and copy Stencil components the same way

packages/stencil-library/src/components/dnn-input/dnn-input.scss, packages/stencil-library/src/components/dnn-select/dnn-select.scss
The controls (for number or date fields, etc.) where not aligned in a form. This makes the input take 100% width of it's container so that those controls align properly.
=> Fixed an issue with input controls alignment

packages/stencil-library/src/components/dnn-modal/dnn-modal.tsx
An event listener was being removed on a element that could possibly not exists.
Closes Drag event needs to be removed only if attached #758
=> Fixed a console error when not using drag on dnn-modal

packages/stencil-library/src/components/dnn-select/dnn-select.tsx
This also improves the behaviour if slotted elements should change after the component is already rendered (loaded).
=> Fixed an issue that caused console errors with dnn-select

packages/stencil-library/src/components/dnn-input/dnn-input.scss, packages/stencil-library/src/components/dnn-select/dnn-select.scss
dnn-input and dnn-select were having alignment issues when used in situations where the label would not have the same font-size as the body.
This makes the label be 1rem so that we can align it with an expected size.
=> Fixed an issue with label alignment of inputs

packages/stencil-library/src/components/dnn-input/dnn-input.scss, packages/stencil-library/src/components/dnn-select/dnn-select.scss
The sizing was using rem instead of em which caused strange behaviors if the root font size happened to not be the same as the font size computed where the component is located.
Closes #809
=> Fixed a sizing/positioning issue with dnn-select and dnn-input

packages/stencil-library/src/components/dnn-sort-icon/dnn-sort-icon.tsx
Removes a warning when changing sortDirection on dnn-sort-icon
Closes #858
=> Removes a warning when changing sortDirection on dnn-sort-icon

packages/stencil-library/stencil.config.ts
This should allow us to then upgrade jest to the latest version
=> Configured Jest to use `new` headless mode

packages/stencil-library/.storybook/manager.ts
Apparently the one we were using was not ESM compatible.
=> Changed import for `create` on storybook theming

packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.tsx
In the browser, both lowercased "jpg" or uppercased "JPG" are allowed for an image file. The check for allowed extensions in the dropzone control was case sensitive block upload of valid image files in dnn-image-cropper and potentially other usages.
=> Fixed a casing issue on validation of allowed extensions

packages/stencil-library/src/components/dnn-image-cropper/types.ts
Closes Wrong typings on localization #954
=> Fixed localization typings issue for image-cropper

packages/stencil-library/src/components.d.ts, packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.tsx, packages/stencil-library/src/components/dnn-richtext/dnn-richtext.scss, packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
This PR does 3 things:
- Makes dnn-richtext form aware so it can be a form input element.
- Fixes a css loading issue with the Jodit editor following package upgrades.
- Fixes an initial form value issue with monaco editor form integration
Part of #992 but does not fully complete it yet, next step is improving validation/accessibility support
=> Made dnn-richtext form aware

packages/stencil-library/src/components/dnn-tabs/dnn-tabs.scss
This PR resolves an issue with `--color-text` not applying to the inactive tab text color.  
It also resolves a typo in a CSS var name that would prevent the style from applying to the visible (currently active) tab text color.
Resolves #997
=> Resolved issue with `--color-text` not applying to inactive tab text color

packages/react-library/lib/components/stencil-generated/index.ts, packages/stencil-library/custom-elements.json, packages/stencil-library/src/components.d.ts, packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss, packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.tsx, packages/stencil-library/src/components/dnn-fieldset/readme.md, packages/stencil-library/src/components/dnn-input/dnn-input.tsx, packages/stencil-library/src/components/dnn-input/readme.md, packages/stencil-library/src/components/dnn-richtext/readme.md, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.scss, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx, packages/stencil-library/src/components/examples/dnn-example-form/readme.md, packages/stencil-library/vscode-data.json
This externalizes the field wrappers into a reusable fieldset component (that potentially could also be used to wrap anything else).
After this PR is merged I'll refactor the exiting fields to consume this component, reduce code and style duplications.
Closes #994
=> Implemented dnn-fieldset component

packages/stencil-library/licenses.json, packages/stencil-library/src/components.d.ts, packages/stencil-library/src/components/dnn-color-input/dnn-color-input.scss, packages/stencil-library/src/components/dnn-color-input/dnn-color-input.tsx, packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss, packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.tsx, packages/stencil-library/src/components/dnn-input/dnn-input.scss, packages/stencil-library/src/components/dnn-input/dnn-input.tsx, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx, packages/stencil-library/src/index.html
This is an initial PR to wrap all inputs in the new reusable dnn-fieldset. Doing this PR so it is easier to review. I'll so additional PRs for other inputs and to improve validation UX.
=> Migrated dnn-color-input and dnn-input in new dnn-fieldset

packages/stencil-library/custom-elements.json, packages/stencil-library/src/components.d.ts, packages/stencil-library/src/components/dnn-color-input/readme.md, packages/stencil-library/src/components/dnn-fieldset/readme.md, packages/stencil-library/src/components/dnn-input/readme.md, packages/stencil-library/src/components/dnn-select/dnn-select.scss, packages/stencil-library/src/components/dnn-select/dnn-select.tsx, packages/stencil-library/src/components/dnn-select/readme.md, packages/stencil-library/src/components/examples/dnn-example-form/readme.md, packages/stencil-library/vscode-data.json
This PR updates dnn-select to consume the reusable dnn-fieldset component created earlier. This avoid code and styles duplications and will enhance maintainability.
It also commits files from a full build that was missed earlier.
Part of #992 work but does not complete it yet
=> Updated dnn-select to use dnn-fieldset

packages/react-library/lib/components/stencil-generated/index.ts, packages/stencil-library/custom-elements.json, packages/stencil-library/src/components.d.ts, packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss, packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.tsx, packages/stencil-library/src/components/dnn-fieldset/readme.md, packages/stencil-library/src/components/dnn-input/dnn-input.tsx, packages/stencil-library/src/components/dnn-textarea/dnn-textarea.scss, packages/stencil-library/src/components/dnn-textarea/dnn-textarea.stories.ts, packages/stencil-library/src/components/dnn-textarea/dnn-textarea.tsx, packages/stencil-library/src/components/dnn-textarea/readme.md, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx, packages/stencil-library/src/components/examples/dnn-example-form/readme.md, packages/stencil-library/vscode-data.json
Also refactored dnn-fieldset so it optinoally supports resizing.
Closes #963
=> Implemented dnn-textarea input field

packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.scss, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx, packages/stencil-library/src/components/examples/dnn-example-form/readme.md
Part of #992
We discussed today about making a dnn-file-input and dnn-image-input but then we wanted to make it flexible enough to allow consumers to replace the input with either a progress or a status. After digging into it, we realized that actually the dropzone is already form aware and that a consumer simply has to wrap it into a dnn-fieldset and do his own logic for progress or status hiding the input as needed.
So this PR just adds such usage example to our dnn-example-form and fixes a css position issue for dnn-fieldset to avoid a different padding left and right to make sure the input is centered within the border.
=> Added examples for usage of files/pictures in forms

packages/stencil-library/custom-elements.json, packages/stencil-library/licenses.json, packages/stencil-library/stencil.config.ts, packages/stencil-library/vscode-data.json
Closes #1094 
Stencil tries to intelligently decide which components should be bundled together for lazy-loading. Somehow this "intelligence" got confused and we ended up with fewer and fewer larger files along the commit history. Rading more about this, we can in the config define how we want our stuff bundled knowing which components usually are used together. The goal is to balance between multiple downloads and small downloads.
This PR manually defines bundles we want.
Examples:
1. dnn-monaco-editor has all the component code and all of monaco code in a single bundle (10.7Mb) that can be forever cached even if we do updates (as long as we don't touch that component).
2. dnn-richtext is in a bundle with all of the Jodit code together (1.1Mb)
3. dnn-color-picker is in a bundle (30Kb) …
=> Fixed an issue that caused too few large bundles

packages/stencil-library/custom-elements.json, packages/stencil-library/src/components.d.ts, packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.tsx, packages/stencil-library/src/components/dnn-autocomplete/readme.md
This is the overall idea we need for #1055 resolution. It adds a `focus` and `blur` method to our input wrapper and forwards the behaviour to the input field we wrap. The input field itself has the logic to add/remove the focused state on the fieldset itself no matter how the focus is gained or lost.
=> Added `focus` and `blur` logic to `dnn-autocomplete`

packages/stencil-library/src/components/dnn-input/dnn-input.tsx
dnn-input supports having a prefix or suffix as slots. Because the label floats as a placeholder until either the component is focused or has a value, this label could partially cover those elements.
With this PR, the prefix or suffix only show once the label slides up.
Closes #1056
=> Fixed an issue that caused label to overlay prefix/suffix

packages/stencil-library/eslint.config.mjs
This is to make our config compatible with newer eslint versions
=> Migrated parserOptions to the new languageOptions

packages/stencil-library/eslint.config.mjs
This is to allow using newer versions of eslint
=> Migrated eslint plugins syntax

packages/stencil-library/src/components/dnn-richtext/dnn-richtext.tsx
The valueChange and valueInput events were firing the Jodit inner events instead of the value strings.
Closes #1156
=> Fixed an issue where inner event was fired with rich-text

packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss, packages/stencil-library/src/index.html
In environments that would have different line-heights, the label position could be off.
=> Fixed an issue that caused label misalignement in dnn-fieldset

packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.tsx, packages/stencil-library/src/components/dnn-textarea/dnn-textarea.tsx
Closes #1181
Also, the height adjustment in the previous PR for textarea was in the wrong lifecycle event as we need the elements to exist before setting styles to them directly.
=> Fixed an issue where label would cover text in dnn-autocomplete

packages/stencil-library/custom-elements.json, packages/stencil-library/src/components.d.ts, packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.tsx, packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.tsx, packages/stencil-library/src/components/dnn-checkbox/readme.md, packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss, packages/stencil-library/src/components/dnn-input/dnn-input.tsx, packages/stencil-library/src/components/dnn-permissions-grid/dnn-permissions-grid.scss, packages/stencil-library/src/components/dnn-permissions-grid/dnn-permissions-grid.tsx, packages/stencil-library/src/components/dnn-select/dnn-select.tsx, packages/stencil-library/src/components/dnn-textarea/dnn-textarea.scss, packages/stencil-library/src/components/dnn-textarea/dnn-textarea.tsx, packages/stencil-library/src/components/dnn-textarea/readme.md, packages/stencil-library/src/components/dnn-toggle/dnn-toggle.tsx, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx, packages/stencil-library/src/index.html, packages/stencil-library/vscode-data.json
Merged fixes from release/0.24.0 back into develop
=> Merged fixes from release/0.24.0 back into develop

packages/stencil-library/src/components/dnn-input/dnn-input.tsx
=> Fixed an issue that made dnn-input label cover 0

packages/stencil-library/src/components/dnn-input/dnn-input.tsx
What was corrected in #1212 only handled the input being of type "number" but having the string "0" also caused the label issue. This PR fixes that.
=> Fixed an issue with 0 string float label

packages/stencil-library/src/components/dnn-input/dnn-input.tsx
Still about #1212 one edge case is the number technically being a "Number" but it's value being NaN instead of undefined.
=> Also handle NaN for label

packages/stencil-library/src/components/dnn-input/dnn-input.tsx
Merged `v0.24.1` beta fixes back into `develop`
=> Merged `v0.24.1` beta fixes back into `develop`

packages/stencil-library/custom-elements.json, packages/stencil-library/src/components.d.ts, packages/stencil-library/src/components/dnn-checkbox/dnn-checkbox.tsx, packages/stencil-library/src/components/dnn-checkbox/readme.md, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx, packages/stencil-library/vscode-data.json
This method can be implemented by consumers if they want a different order when using useIntermediate.
=> Added prop to cusomize tri-state order of dnn-checkbox

package-lock.json, packages/stencil-library/custom-elements.json, packages/stencil-library/licenses.json, packages/stencil-library/src/components/dnn-dropzone/dnn-dropzone.scss, packages/stencil-library/vscode-data.json
Updated border and background color for `dnn-dropzone` for compatibility with DNN 10.  The screenshots below are based on the DNN CSS variables hard-coded in `index.html` so there may be a slight variation between them and what is actually in DNN 10.  We may want to consider updating these in DNN elements to match DNN 10 now that it has been implemented in DNN 10.
Resolves #1246
=> Updated border and background color for `dnn-dropzone` for compatibility with DNN 10

packages/stencil-library/custom-elements.json, packages/stencil-library/src/components/dnn-autocomplete/dnn-autocomplete.scss, packages/stencil-library/src/components/dnn-color-input/dnn-color-input.scss, packages/stencil-library/src/components/dnn-color-input/readme.md, packages/stencil-library/src/components/dnn-fieldset/dnn-fieldset.scss, packages/stencil-library/src/components/dnn-fieldset/readme.md, packages/stencil-library/src/components/dnn-input/dnn-input.scss, packages/stencil-library/src/components/dnn-input/readme.md, packages/stencil-library/src/components/dnn-select/dnn-select.scss, packages/stencil-library/src/components/dnn-select/readme.md, packages/stencil-library/src/components/dnn-textarea/dnn-textarea.scss, packages/stencil-library/src/components/dnn-textarea/readme.md
We created a way for people to be able to customize styles of input elements with some css-variables, however some of the variables defined were not being passed down to the wrapping fieldset causing confusion.
Also the namin of those variables was a bit different from component to component, this PR also harmonizes that naming for avoiding further confusion. This rename is a slight breaking change, so I'll call attention to it in the release notes.
Example of some custom usage on a dark theme:
Closes #1251
=> Fixed some issues with css-variables of inputs

packages/stencil-library/src/components/dnn-button/dnn-button.stories.ts, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
dnn-button had some properties renamed and this was a breaking change but storybook was not updated to use the new property names.
Closes #1258
=> Fixed storybook to account for breaking changes

packages/stencil-library/src/components/dnn-button/dnn-button.tsx, packages/stencil-library/src/components/dnn-select/dnn-select.tsx, packages/stencil-library/src/components/examples/dnn-example-form/dnn-example-form.tsx
When feeding <option> elements in the slot of dnn-select with a pre-selected item (selected = true) like when used on a form to edit something existing instead of doing something new; The underlying initialization logic was not setting the form level value upon initialization. This caused a discrepancy as it would display as valid but would prevent form submission because the form was not valid.
Also the form `onInvalid` event was not being fired making it even more confusing. This part was fixed in the dnn-button logic.
=> Fixed an issue where dnn-select was not being properly initialized

packages/stencil-library/package.json
This npm script was accidently removed during the storybook refactoring
=> Adds back storybook deployment

package-lock.json, packages/stencil-library/package.json
We only use vitest but we do not specify the `vite` version to use.
=> Added `vite` dev-dependency to lock in version
